/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ca.efendi.datafeeds.impl;

import aQute.bnd.annotation.ProviderType;

import ca.efendi.datafeeds.model.FtpSubscription;
import ca.efendi.datafeeds.service.FtpSubscriptionLocalServiceUtil;

/**
 * The extended model base implementation for the FtpSubscription service. Represents a row in the &quot;FE_FtpSubscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FtpSubscriptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FtpSubscriptionImpl
 * @see FtpSubscription
 * @generated
 */
@ProviderType
public abstract class FtpSubscriptionBaseImpl extends FtpSubscriptionModelImpl
	implements FtpSubscription {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ftp subscription model instance should use the {@link FtpSubscription} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FtpSubscriptionLocalServiceUtil.addFtpSubscription(this);
		}
		else {
			FtpSubscriptionLocalServiceUtil.updateFtpSubscription(this);
		}
	}
}