/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ca.efendi.datafeeds.model.impl;

import aQute.bnd.annotation.ProviderType;

import ca.efendi.datafeeds.model.CJProduct;
import ca.efendi.datafeeds.model.CJProductModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CJProduct service. Represents a row in the &quot;FE_CJProduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CJProductModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CJProductImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CJProductImpl
 * @see CJProduct
 * @see CJProductModel
 * @generated
 */
@ProviderType
public class CJProductModelImpl extends BaseModelImpl<CJProduct>
	implements CJProductModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a c j product model instance should use the {@link CJProduct} interface instead.
	 */
	public static final String TABLE_NAME = "FE_CJProduct";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "productId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "programName", Types.VARCHAR },
			{ "catalogName", Types.VARCHAR },
			{ "sku", Types.VARCHAR },
			{ "programUrl", Types.VARCHAR },
			{ "lastUpdated", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "keywords", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "manufacturer", Types.VARCHAR },
			{ "manufacturerId", Types.VARCHAR },
			{ "currency_", Types.VARCHAR },
			{ "price", Types.VARCHAR },
			{ "buyUrl", Types.VARCHAR },
			{ "impressionUrl", Types.VARCHAR },
			{ "imageUrl", Types.VARCHAR },
			{ "inStock", Types.VARCHAR },
			{ "viewCount", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("programName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("catalogName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sku", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("programUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastUpdated", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("keywords", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("manufacturer", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("manufacturerId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("currency_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("price", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("buyUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("impressionUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("inStock", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("viewCount", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table FE_CJProduct (uuid_ VARCHAR(75) null,productId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,programName VARCHAR(75) null,catalogName VARCHAR(75) null,sku VARCHAR(75) null,programUrl VARCHAR(75) null,lastUpdated VARCHAR(75) null,name VARCHAR(75) null,keywords VARCHAR(75) null,description VARCHAR(75) null,manufacturer VARCHAR(75) null,manufacturerId VARCHAR(75) null,currency_ VARCHAR(75) null,price VARCHAR(75) null,buyUrl VARCHAR(75) null,impressionUrl VARCHAR(75) null,imageUrl VARCHAR(75) null,inStock VARCHAR(75) null,viewCount INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table FE_CJProduct";
	public static final String ORDER_BY_JPQL = " ORDER BY cjProduct.manufacturer ASC, cjProduct.name DESC";
	public static final String ORDER_BY_SQL = " ORDER BY FE_CJProduct.manufacturer ASC, FE_CJProduct.name DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(ca.efendi.datafeeds.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.ca.efendi.datafeeds.model.CJProduct"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(ca.efendi.datafeeds.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.ca.efendi.datafeeds.model.CJProduct"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(ca.efendi.datafeeds.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.ca.efendi.datafeeds.model.CJProduct"),
			true);
	public static final long CATALOGNAME_COLUMN_BITMASK = 1L;
	public static final long COMPANYID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long MANUFACTURER_COLUMN_BITMASK = 8L;
	public static final long PROGRAMNAME_COLUMN_BITMASK = 16L;
	public static final long SKU_COLUMN_BITMASK = 32L;
	public static final long UUID_COLUMN_BITMASK = 64L;
	public static final long NAME_COLUMN_BITMASK = 128L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(ca.efendi.datafeeds.service.util.PropsUtil.get(
				"lock.expiration.time.ca.efendi.datafeeds.model.CJProduct"));

	public CJProductModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _productId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProductId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _productId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CJProduct.class;
	}

	@Override
	public String getModelClassName() {
		return CJProduct.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("productId", getProductId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("programName", getProgramName());
		attributes.put("catalogName", getCatalogName());
		attributes.put("sku", getSku());
		attributes.put("programUrl", getProgramUrl());
		attributes.put("lastUpdated", getLastUpdated());
		attributes.put("name", getName());
		attributes.put("keywords", getKeywords());
		attributes.put("description", getDescription());
		attributes.put("manufacturer", getManufacturer());
		attributes.put("manufacturerId", getManufacturerId());
		attributes.put("currency", getCurrency());
		attributes.put("price", getPrice());
		attributes.put("buyUrl", getBuyUrl());
		attributes.put("impressionUrl", getImpressionUrl());
		attributes.put("imageUrl", getImageUrl());
		attributes.put("inStock", getInStock());
		attributes.put("viewCount", getViewCount());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long productId = (Long)attributes.get("productId");

		if (productId != null) {
			setProductId(productId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String programName = (String)attributes.get("programName");

		if (programName != null) {
			setProgramName(programName);
		}

		String catalogName = (String)attributes.get("catalogName");

		if (catalogName != null) {
			setCatalogName(catalogName);
		}

		String sku = (String)attributes.get("sku");

		if (sku != null) {
			setSku(sku);
		}

		String programUrl = (String)attributes.get("programUrl");

		if (programUrl != null) {
			setProgramUrl(programUrl);
		}

		String lastUpdated = (String)attributes.get("lastUpdated");

		if (lastUpdated != null) {
			setLastUpdated(lastUpdated);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String keywords = (String)attributes.get("keywords");

		if (keywords != null) {
			setKeywords(keywords);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String manufacturer = (String)attributes.get("manufacturer");

		if (manufacturer != null) {
			setManufacturer(manufacturer);
		}

		String manufacturerId = (String)attributes.get("manufacturerId");

		if (manufacturerId != null) {
			setManufacturerId(manufacturerId);
		}

		String currency = (String)attributes.get("currency");

		if (currency != null) {
			setCurrency(currency);
		}

		String price = (String)attributes.get("price");

		if (price != null) {
			setPrice(price);
		}

		String buyUrl = (String)attributes.get("buyUrl");

		if (buyUrl != null) {
			setBuyUrl(buyUrl);
		}

		String impressionUrl = (String)attributes.get("impressionUrl");

		if (impressionUrl != null) {
			setImpressionUrl(impressionUrl);
		}

		String imageUrl = (String)attributes.get("imageUrl");

		if (imageUrl != null) {
			setImageUrl(imageUrl);
		}

		String inStock = (String)attributes.get("inStock");

		if (inStock != null) {
			setInStock(inStock);
		}

		Integer viewCount = (Integer)attributes.get("viewCount");

		if (viewCount != null) {
			setViewCount(viewCount);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getProductId() {
		return _productId;
	}

	@Override
	public void setProductId(long productId) {
		_productId = productId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getProgramName() {
		if (_programName == null) {
			return StringPool.BLANK;
		}
		else {
			return _programName;
		}
	}

	@Override
	public void setProgramName(String programName) {
		_columnBitmask |= PROGRAMNAME_COLUMN_BITMASK;

		if (_originalProgramName == null) {
			_originalProgramName = _programName;
		}

		_programName = programName;
	}

	public String getOriginalProgramName() {
		return GetterUtil.getString(_originalProgramName);
	}

	@Override
	public String getCatalogName() {
		if (_catalogName == null) {
			return StringPool.BLANK;
		}
		else {
			return _catalogName;
		}
	}

	@Override
	public void setCatalogName(String catalogName) {
		_columnBitmask |= CATALOGNAME_COLUMN_BITMASK;

		if (_originalCatalogName == null) {
			_originalCatalogName = _catalogName;
		}

		_catalogName = catalogName;
	}

	public String getOriginalCatalogName() {
		return GetterUtil.getString(_originalCatalogName);
	}

	@Override
	public String getSku() {
		if (_sku == null) {
			return StringPool.BLANK;
		}
		else {
			return _sku;
		}
	}

	@Override
	public void setSku(String sku) {
		_columnBitmask |= SKU_COLUMN_BITMASK;

		if (_originalSku == null) {
			_originalSku = _sku;
		}

		_sku = sku;
	}

	public String getOriginalSku() {
		return GetterUtil.getString(_originalSku);
	}

	@Override
	public String getProgramUrl() {
		if (_programUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _programUrl;
		}
	}

	@Override
	public void setProgramUrl(String programUrl) {
		_programUrl = programUrl;
	}

	@Override
	public String getLastUpdated() {
		if (_lastUpdated == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastUpdated;
		}
	}

	@Override
	public void setLastUpdated(String lastUpdated) {
		_lastUpdated = lastUpdated;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	@Override
	public String getKeywords() {
		if (_keywords == null) {
			return StringPool.BLANK;
		}
		else {
			return _keywords;
		}
	}

	@Override
	public void setKeywords(String keywords) {
		_keywords = keywords;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getManufacturer() {
		if (_manufacturer == null) {
			return StringPool.BLANK;
		}
		else {
			return _manufacturer;
		}
	}

	@Override
	public void setManufacturer(String manufacturer) {
		_columnBitmask = -1L;

		if (_originalManufacturer == null) {
			_originalManufacturer = _manufacturer;
		}

		_manufacturer = manufacturer;
	}

	public String getOriginalManufacturer() {
		return GetterUtil.getString(_originalManufacturer);
	}

	@Override
	public String getManufacturerId() {
		if (_manufacturerId == null) {
			return StringPool.BLANK;
		}
		else {
			return _manufacturerId;
		}
	}

	@Override
	public void setManufacturerId(String manufacturerId) {
		_manufacturerId = manufacturerId;
	}

	@Override
	public String getCurrency() {
		if (_currency == null) {
			return StringPool.BLANK;
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		_currency = currency;
	}

	@Override
	public String getPrice() {
		if (_price == null) {
			return StringPool.BLANK;
		}
		else {
			return _price;
		}
	}

	@Override
	public void setPrice(String price) {
		_price = price;
	}

	@Override
	public String getBuyUrl() {
		if (_buyUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _buyUrl;
		}
	}

	@Override
	public void setBuyUrl(String buyUrl) {
		_buyUrl = buyUrl;
	}

	@Override
	public String getImpressionUrl() {
		if (_impressionUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _impressionUrl;
		}
	}

	@Override
	public void setImpressionUrl(String impressionUrl) {
		_impressionUrl = impressionUrl;
	}

	@Override
	public String getImageUrl() {
		if (_imageUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageUrl;
		}
	}

	@Override
	public void setImageUrl(String imageUrl) {
		_imageUrl = imageUrl;
	}

	@Override
	public String getInStock() {
		if (_inStock == null) {
			return StringPool.BLANK;
		}
		else {
			return _inStock;
		}
	}

	@Override
	public void setInStock(String inStock) {
		_inStock = inStock;
	}

	@Override
	public int getViewCount() {
		return _viewCount;
	}

	@Override
	public void setViewCount(int viewCount) {
		_viewCount = viewCount;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				CJProduct.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CJProduct.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CJProduct toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CJProduct)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CJProductImpl cjProductImpl = new CJProductImpl();

		cjProductImpl.setUuid(getUuid());
		cjProductImpl.setProductId(getProductId());
		cjProductImpl.setGroupId(getGroupId());
		cjProductImpl.setCompanyId(getCompanyId());
		cjProductImpl.setUserId(getUserId());
		cjProductImpl.setUserName(getUserName());
		cjProductImpl.setCreateDate(getCreateDate());
		cjProductImpl.setModifiedDate(getModifiedDate());
		cjProductImpl.setProgramName(getProgramName());
		cjProductImpl.setCatalogName(getCatalogName());
		cjProductImpl.setSku(getSku());
		cjProductImpl.setProgramUrl(getProgramUrl());
		cjProductImpl.setLastUpdated(getLastUpdated());
		cjProductImpl.setName(getName());
		cjProductImpl.setKeywords(getKeywords());
		cjProductImpl.setDescription(getDescription());
		cjProductImpl.setManufacturer(getManufacturer());
		cjProductImpl.setManufacturerId(getManufacturerId());
		cjProductImpl.setCurrency(getCurrency());
		cjProductImpl.setPrice(getPrice());
		cjProductImpl.setBuyUrl(getBuyUrl());
		cjProductImpl.setImpressionUrl(getImpressionUrl());
		cjProductImpl.setImageUrl(getImageUrl());
		cjProductImpl.setInStock(getInStock());
		cjProductImpl.setViewCount(getViewCount());

		cjProductImpl.resetOriginalValues();

		return cjProductImpl;
	}

	@Override
	public int compareTo(CJProduct cjProduct) {
		int value = 0;

		value = getManufacturer().compareTo(cjProduct.getManufacturer());

		if (value != 0) {
			return value;
		}

		value = getName().compareTo(cjProduct.getName());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CJProduct)) {
			return false;
		}

		CJProduct cjProduct = (CJProduct)obj;

		long primaryKey = cjProduct.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CJProductModelImpl cjProductModelImpl = this;

		cjProductModelImpl._originalUuid = cjProductModelImpl._uuid;

		cjProductModelImpl._originalGroupId = cjProductModelImpl._groupId;

		cjProductModelImpl._setOriginalGroupId = false;

		cjProductModelImpl._originalCompanyId = cjProductModelImpl._companyId;

		cjProductModelImpl._setOriginalCompanyId = false;

		cjProductModelImpl._setModifiedDate = false;

		cjProductModelImpl._originalProgramName = cjProductModelImpl._programName;

		cjProductModelImpl._originalCatalogName = cjProductModelImpl._catalogName;

		cjProductModelImpl._originalSku = cjProductModelImpl._sku;

		cjProductModelImpl._originalManufacturer = cjProductModelImpl._manufacturer;

		cjProductModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CJProduct> toCacheModel() {
		CJProductCacheModel cjProductCacheModel = new CJProductCacheModel();

		cjProductCacheModel.uuid = getUuid();

		String uuid = cjProductCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			cjProductCacheModel.uuid = null;
		}

		cjProductCacheModel.productId = getProductId();

		cjProductCacheModel.groupId = getGroupId();

		cjProductCacheModel.companyId = getCompanyId();

		cjProductCacheModel.userId = getUserId();

		cjProductCacheModel.userName = getUserName();

		String userName = cjProductCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cjProductCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cjProductCacheModel.createDate = createDate.getTime();
		}
		else {
			cjProductCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cjProductCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cjProductCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cjProductCacheModel.programName = getProgramName();

		String programName = cjProductCacheModel.programName;

		if ((programName != null) && (programName.length() == 0)) {
			cjProductCacheModel.programName = null;
		}

		cjProductCacheModel.catalogName = getCatalogName();

		String catalogName = cjProductCacheModel.catalogName;

		if ((catalogName != null) && (catalogName.length() == 0)) {
			cjProductCacheModel.catalogName = null;
		}

		cjProductCacheModel.sku = getSku();

		String sku = cjProductCacheModel.sku;

		if ((sku != null) && (sku.length() == 0)) {
			cjProductCacheModel.sku = null;
		}

		cjProductCacheModel.programUrl = getProgramUrl();

		String programUrl = cjProductCacheModel.programUrl;

		if ((programUrl != null) && (programUrl.length() == 0)) {
			cjProductCacheModel.programUrl = null;
		}

		cjProductCacheModel.lastUpdated = getLastUpdated();

		String lastUpdated = cjProductCacheModel.lastUpdated;

		if ((lastUpdated != null) && (lastUpdated.length() == 0)) {
			cjProductCacheModel.lastUpdated = null;
		}

		cjProductCacheModel.name = getName();

		String name = cjProductCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			cjProductCacheModel.name = null;
		}

		cjProductCacheModel.keywords = getKeywords();

		String keywords = cjProductCacheModel.keywords;

		if ((keywords != null) && (keywords.length() == 0)) {
			cjProductCacheModel.keywords = null;
		}

		cjProductCacheModel.description = getDescription();

		String description = cjProductCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			cjProductCacheModel.description = null;
		}

		cjProductCacheModel.manufacturer = getManufacturer();

		String manufacturer = cjProductCacheModel.manufacturer;

		if ((manufacturer != null) && (manufacturer.length() == 0)) {
			cjProductCacheModel.manufacturer = null;
		}

		cjProductCacheModel.manufacturerId = getManufacturerId();

		String manufacturerId = cjProductCacheModel.manufacturerId;

		if ((manufacturerId != null) && (manufacturerId.length() == 0)) {
			cjProductCacheModel.manufacturerId = null;
		}

		cjProductCacheModel.currency = getCurrency();

		String currency = cjProductCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			cjProductCacheModel.currency = null;
		}

		cjProductCacheModel.price = getPrice();

		String price = cjProductCacheModel.price;

		if ((price != null) && (price.length() == 0)) {
			cjProductCacheModel.price = null;
		}

		cjProductCacheModel.buyUrl = getBuyUrl();

		String buyUrl = cjProductCacheModel.buyUrl;

		if ((buyUrl != null) && (buyUrl.length() == 0)) {
			cjProductCacheModel.buyUrl = null;
		}

		cjProductCacheModel.impressionUrl = getImpressionUrl();

		String impressionUrl = cjProductCacheModel.impressionUrl;

		if ((impressionUrl != null) && (impressionUrl.length() == 0)) {
			cjProductCacheModel.impressionUrl = null;
		}

		cjProductCacheModel.imageUrl = getImageUrl();

		String imageUrl = cjProductCacheModel.imageUrl;

		if ((imageUrl != null) && (imageUrl.length() == 0)) {
			cjProductCacheModel.imageUrl = null;
		}

		cjProductCacheModel.inStock = getInStock();

		String inStock = cjProductCacheModel.inStock;

		if ((inStock != null) && (inStock.length() == 0)) {
			cjProductCacheModel.inStock = null;
		}

		cjProductCacheModel.viewCount = getViewCount();

		return cjProductCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(51);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", productId=");
		sb.append(getProductId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", programName=");
		sb.append(getProgramName());
		sb.append(", catalogName=");
		sb.append(getCatalogName());
		sb.append(", sku=");
		sb.append(getSku());
		sb.append(", programUrl=");
		sb.append(getProgramUrl());
		sb.append(", lastUpdated=");
		sb.append(getLastUpdated());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", keywords=");
		sb.append(getKeywords());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", manufacturer=");
		sb.append(getManufacturer());
		sb.append(", manufacturerId=");
		sb.append(getManufacturerId());
		sb.append(", currency=");
		sb.append(getCurrency());
		sb.append(", price=");
		sb.append(getPrice());
		sb.append(", buyUrl=");
		sb.append(getBuyUrl());
		sb.append(", impressionUrl=");
		sb.append(getImpressionUrl());
		sb.append(", imageUrl=");
		sb.append(getImageUrl());
		sb.append(", inStock=");
		sb.append(getInStock());
		sb.append(", viewCount=");
		sb.append(getViewCount());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(79);

		sb.append("<model><model-name>");
		sb.append("ca.efendi.datafeeds.model.CJProduct");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productId</column-name><column-value><![CDATA[");
		sb.append(getProductId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>programName</column-name><column-value><![CDATA[");
		sb.append(getProgramName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>catalogName</column-name><column-value><![CDATA[");
		sb.append(getCatalogName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sku</column-name><column-value><![CDATA[");
		sb.append(getSku());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>programUrl</column-name><column-value><![CDATA[");
		sb.append(getProgramUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastUpdated</column-name><column-value><![CDATA[");
		sb.append(getLastUpdated());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keywords</column-name><column-value><![CDATA[");
		sb.append(getKeywords());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>manufacturer</column-name><column-value><![CDATA[");
		sb.append(getManufacturer());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>manufacturerId</column-name><column-value><![CDATA[");
		sb.append(getManufacturerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currency</column-name><column-value><![CDATA[");
		sb.append(getCurrency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>price</column-name><column-value><![CDATA[");
		sb.append(getPrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>buyUrl</column-name><column-value><![CDATA[");
		sb.append(getBuyUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>impressionUrl</column-name><column-value><![CDATA[");
		sb.append(getImpressionUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageUrl</column-name><column-value><![CDATA[");
		sb.append(getImageUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inStock</column-name><column-value><![CDATA[");
		sb.append(getInStock());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viewCount</column-name><column-value><![CDATA[");
		sb.append(getViewCount());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CJProduct.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CJProduct.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _productId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _programName;
	private String _originalProgramName;
	private String _catalogName;
	private String _originalCatalogName;
	private String _sku;
	private String _originalSku;
	private String _programUrl;
	private String _lastUpdated;
	private String _name;
	private String _keywords;
	private String _description;
	private String _manufacturer;
	private String _originalManufacturer;
	private String _manufacturerId;
	private String _currency;
	private String _price;
	private String _buyUrl;
	private String _impressionUrl;
	private String _imageUrl;
	private String _inStock;
	private int _viewCount;
	private long _columnBitmask;
	private CJProduct _escapedModel;
}