create table FE_CJProduct (
	uuid_ VARCHAR(75) null,
	productId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	programName VARCHAR(75) null,
	catalogName VARCHAR(75) null,
	sku VARCHAR(77) null,
	programUrl VARCHAR(75) null,
	lastUpdated VARCHAR(75) null,
	name VARCHAR(1024) null,
	keywords VARCHAR(1024) null,
	description VARCHAR(2048) null,
	manufacturer VARCHAR(75) null,
	manufacturerId VARCHAR(75) null,
	currency_ VARCHAR(75) null,
	price VARCHAR(75) null,
	buyUrl VARCHAR(1024) null,
	impressionUrl VARCHAR(75) null,
	imageUrl VARCHAR(1024) null,
	inStock VARCHAR(75) null,
	viewCount INTEGER,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	subtitle VARCHAR(75) null,
	urlTitle VARCHAR(75) null,
	content VARCHAR(75) null,
	displayDate DATE null,
	coverImageCaption VARCHAR(75) null,
	coverImageFileEntryId LONG,
	coverImageURL VARCHAR(75) null,
	smallImage BOOLEAN,
	smallImageFileEntryId LONG,
	smallImageId LONG,
	smallImageURL VARCHAR(75) null
);

create table FE_FtpSubscription (
	ftpSubscriptionId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	ftpHost VARCHAR(75) null,
	ftpUser VARCHAR(75) null,
	ftpPassword VARCHAR(75) null,
	ftpFolder VARCHAR(75) null,
	ftpFile VARCHAR(75) null,
	ftpDatafeedName VARCHAR(75) null,
	ftpDatafeedDescription VARCHAR(75) null
);