/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ca.efendi.datafeeds.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CJProduct service. Represents a row in the &quot;FE_CJProduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ca.efendi.datafeeds.model.impl.CJProductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ca.efendi.datafeeds.model.impl.CJProductImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CJProduct
 * @see ca.efendi.datafeeds.model.impl.CJProductImpl
 * @see ca.efendi.datafeeds.model.impl.CJProductModelImpl
 * @generated
 */
@ProviderType
public interface CJProductModel extends BaseModel<CJProduct>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c j product model instance should use the {@link CJProduct} interface instead.
	 */

	/**
	 * Returns the primary key of this c j product.
	 *
	 * @return the primary key of this c j product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this c j product.
	 *
	 * @param primaryKey the primary key of this c j product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this c j product.
	 *
	 * @return the uuid of this c j product
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this c j product.
	 *
	 * @param uuid the uuid of this c j product
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the product ID of this c j product.
	 *
	 * @return the product ID of this c j product
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this c j product.
	 *
	 * @param productId the product ID of this c j product
	 */
	public void setProductId(long productId);

	/**
	 * Returns the group ID of this c j product.
	 *
	 * @return the group ID of this c j product
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this c j product.
	 *
	 * @param groupId the group ID of this c j product
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this c j product.
	 *
	 * @return the company ID of this c j product
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this c j product.
	 *
	 * @param companyId the company ID of this c j product
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this c j product.
	 *
	 * @return the user ID of this c j product
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this c j product.
	 *
	 * @param userId the user ID of this c j product
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c j product.
	 *
	 * @return the user uuid of this c j product
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this c j product.
	 *
	 * @param userUuid the user uuid of this c j product
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this c j product.
	 *
	 * @return the user name of this c j product
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this c j product.
	 *
	 * @param userName the user name of this c j product
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this c j product.
	 *
	 * @return the create date of this c j product
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this c j product.
	 *
	 * @param createDate the create date of this c j product
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c j product.
	 *
	 * @return the modified date of this c j product
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c j product.
	 *
	 * @param modifiedDate the modified date of this c j product
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the program name of this c j product.
	 *
	 * @return the program name of this c j product
	 */
	@AutoEscape
	public String getProgramName();

	/**
	 * Sets the program name of this c j product.
	 *
	 * @param programName the program name of this c j product
	 */
	public void setProgramName(String programName);

	/**
	 * Returns the catalog name of this c j product.
	 *
	 * @return the catalog name of this c j product
	 */
	@AutoEscape
	public String getCatalogName();

	/**
	 * Sets the catalog name of this c j product.
	 *
	 * @param catalogName the catalog name of this c j product
	 */
	public void setCatalogName(String catalogName);

	/**
	 * Returns the sku of this c j product.
	 *
	 * @return the sku of this c j product
	 */
	@AutoEscape
	public String getSku();

	/**
	 * Sets the sku of this c j product.
	 *
	 * @param sku the sku of this c j product
	 */
	public void setSku(String sku);

	/**
	 * Returns the program url of this c j product.
	 *
	 * @return the program url of this c j product
	 */
	@AutoEscape
	public String getProgramUrl();

	/**
	 * Sets the program url of this c j product.
	 *
	 * @param programUrl the program url of this c j product
	 */
	public void setProgramUrl(String programUrl);

	/**
	 * Returns the last updated of this c j product.
	 *
	 * @return the last updated of this c j product
	 */
	@AutoEscape
	public String getLastUpdated();

	/**
	 * Sets the last updated of this c j product.
	 *
	 * @param lastUpdated the last updated of this c j product
	 */
	public void setLastUpdated(String lastUpdated);

	/**
	 * Returns the name of this c j product.
	 *
	 * @return the name of this c j product
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this c j product.
	 *
	 * @param name the name of this c j product
	 */
	public void setName(String name);

	/**
	 * Returns the keywords of this c j product.
	 *
	 * @return the keywords of this c j product
	 */
	@AutoEscape
	public String getKeywords();

	/**
	 * Sets the keywords of this c j product.
	 *
	 * @param keywords the keywords of this c j product
	 */
	public void setKeywords(String keywords);

	/**
	 * Returns the description of this c j product.
	 *
	 * @return the description of this c j product
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this c j product.
	 *
	 * @param description the description of this c j product
	 */
	public void setDescription(String description);

	/**
	 * Returns the manufacturer of this c j product.
	 *
	 * @return the manufacturer of this c j product
	 */
	@AutoEscape
	public String getManufacturer();

	/**
	 * Sets the manufacturer of this c j product.
	 *
	 * @param manufacturer the manufacturer of this c j product
	 */
	public void setManufacturer(String manufacturer);

	/**
	 * Returns the manufacturer ID of this c j product.
	 *
	 * @return the manufacturer ID of this c j product
	 */
	@AutoEscape
	public String getManufacturerId();

	/**
	 * Sets the manufacturer ID of this c j product.
	 *
	 * @param manufacturerId the manufacturer ID of this c j product
	 */
	public void setManufacturerId(String manufacturerId);

	/**
	 * Returns the currency of this c j product.
	 *
	 * @return the currency of this c j product
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this c j product.
	 *
	 * @param currency the currency of this c j product
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the price of this c j product.
	 *
	 * @return the price of this c j product
	 */
	@AutoEscape
	public String getPrice();

	/**
	 * Sets the price of this c j product.
	 *
	 * @param price the price of this c j product
	 */
	public void setPrice(String price);

	/**
	 * Returns the buy url of this c j product.
	 *
	 * @return the buy url of this c j product
	 */
	@AutoEscape
	public String getBuyUrl();

	/**
	 * Sets the buy url of this c j product.
	 *
	 * @param buyUrl the buy url of this c j product
	 */
	public void setBuyUrl(String buyUrl);

	/**
	 * Returns the impression url of this c j product.
	 *
	 * @return the impression url of this c j product
	 */
	@AutoEscape
	public String getImpressionUrl();

	/**
	 * Sets the impression url of this c j product.
	 *
	 * @param impressionUrl the impression url of this c j product
	 */
	public void setImpressionUrl(String impressionUrl);

	/**
	 * Returns the image url of this c j product.
	 *
	 * @return the image url of this c j product
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this c j product.
	 *
	 * @param imageUrl the image url of this c j product
	 */
	public void setImageUrl(String imageUrl);

	/**
	 * Returns the in stock of this c j product.
	 *
	 * @return the in stock of this c j product
	 */
	@AutoEscape
	public String getInStock();

	/**
	 * Sets the in stock of this c j product.
	 *
	 * @param inStock the in stock of this c j product
	 */
	public void setInStock(String inStock);

	/**
	 * Returns the view count of this c j product.
	 *
	 * @return the view count of this c j product
	 */
	public int getViewCount();

	/**
	 * Sets the view count of this c j product.
	 *
	 * @param viewCount the view count of this c j product
	 */
	public void setViewCount(int viewCount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ca.efendi.datafeeds.model.CJProduct cjProduct);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ca.efendi.datafeeds.model.CJProduct> toCacheModel();

	@Override
	public ca.efendi.datafeeds.model.CJProduct toEscapedModel();

	@Override
	public ca.efendi.datafeeds.model.CJProduct toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}