/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ca.efendi.datafeeds.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FtpSubscription service. Represents a row in the &quot;FE_FtpSubscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ca.efendi.datafeeds.model.impl.FtpSubscriptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ca.efendi.datafeeds.model.impl.FtpSubscriptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FtpSubscription
 * @see ca.efendi.datafeeds.model.impl.FtpSubscriptionImpl
 * @see ca.efendi.datafeeds.model.impl.FtpSubscriptionModelImpl
 * @generated
 */
@ProviderType
public interface FtpSubscriptionModel extends BaseModel<FtpSubscription>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ftp subscription model instance should use the {@link FtpSubscription} interface instead.
	 */

	/**
	 * Returns the primary key of this ftp subscription.
	 *
	 * @return the primary key of this ftp subscription
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ftp subscription.
	 *
	 * @param primaryKey the primary key of this ftp subscription
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ftp subscription ID of this ftp subscription.
	 *
	 * @return the ftp subscription ID of this ftp subscription
	 */
	public long getFtpSubscriptionId();

	/**
	 * Sets the ftp subscription ID of this ftp subscription.
	 *
	 * @param ftpSubscriptionId the ftp subscription ID of this ftp subscription
	 */
	public void setFtpSubscriptionId(long ftpSubscriptionId);

	/**
	 * Returns the group ID of this ftp subscription.
	 *
	 * @return the group ID of this ftp subscription
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ftp subscription.
	 *
	 * @param groupId the group ID of this ftp subscription
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ftp subscription.
	 *
	 * @return the company ID of this ftp subscription
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ftp subscription.
	 *
	 * @param companyId the company ID of this ftp subscription
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ftp subscription.
	 *
	 * @return the user ID of this ftp subscription
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ftp subscription.
	 *
	 * @param userId the user ID of this ftp subscription
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ftp subscription.
	 *
	 * @return the user uuid of this ftp subscription
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ftp subscription.
	 *
	 * @param userUuid the user uuid of this ftp subscription
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ftp subscription.
	 *
	 * @return the user name of this ftp subscription
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ftp subscription.
	 *
	 * @param userName the user name of this ftp subscription
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ftp subscription.
	 *
	 * @return the create date of this ftp subscription
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ftp subscription.
	 *
	 * @param createDate the create date of this ftp subscription
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ftp subscription.
	 *
	 * @return the modified date of this ftp subscription
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ftp subscription.
	 *
	 * @param modifiedDate the modified date of this ftp subscription
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ftp host of this ftp subscription.
	 *
	 * @return the ftp host of this ftp subscription
	 */
	@AutoEscape
	public String getFtpHost();

	/**
	 * Sets the ftp host of this ftp subscription.
	 *
	 * @param ftpHost the ftp host of this ftp subscription
	 */
	public void setFtpHost(String ftpHost);

	/**
	 * Returns the ftp user of this ftp subscription.
	 *
	 * @return the ftp user of this ftp subscription
	 */
	@AutoEscape
	public String getFtpUser();

	/**
	 * Sets the ftp user of this ftp subscription.
	 *
	 * @param ftpUser the ftp user of this ftp subscription
	 */
	public void setFtpUser(String ftpUser);

	/**
	 * Returns the ftp password of this ftp subscription.
	 *
	 * @return the ftp password of this ftp subscription
	 */
	@AutoEscape
	public String getFtpPassword();

	/**
	 * Sets the ftp password of this ftp subscription.
	 *
	 * @param ftpPassword the ftp password of this ftp subscription
	 */
	public void setFtpPassword(String ftpPassword);

	/**
	 * Returns the ftp folder of this ftp subscription.
	 *
	 * @return the ftp folder of this ftp subscription
	 */
	@AutoEscape
	public String getFtpFolder();

	/**
	 * Sets the ftp folder of this ftp subscription.
	 *
	 * @param ftpFolder the ftp folder of this ftp subscription
	 */
	public void setFtpFolder(String ftpFolder);

	/**
	 * Returns the ftp file of this ftp subscription.
	 *
	 * @return the ftp file of this ftp subscription
	 */
	@AutoEscape
	public String getFtpFile();

	/**
	 * Sets the ftp file of this ftp subscription.
	 *
	 * @param ftpFile the ftp file of this ftp subscription
	 */
	public void setFtpFile(String ftpFile);

	/**
	 * Returns the ftp datafeed name of this ftp subscription.
	 *
	 * @return the ftp datafeed name of this ftp subscription
	 */
	@AutoEscape
	public String getFtpDatafeedName();

	/**
	 * Sets the ftp datafeed name of this ftp subscription.
	 *
	 * @param ftpDatafeedName the ftp datafeed name of this ftp subscription
	 */
	public void setFtpDatafeedName(String ftpDatafeedName);

	/**
	 * Returns the ftp datafeed description of this ftp subscription.
	 *
	 * @return the ftp datafeed description of this ftp subscription
	 */
	@AutoEscape
	public String getFtpDatafeedDescription();

	/**
	 * Sets the ftp datafeed description of this ftp subscription.
	 *
	 * @param ftpDatafeedDescription the ftp datafeed description of this ftp subscription
	 */
	public void setFtpDatafeedDescription(String ftpDatafeedDescription);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ca.efendi.datafeeds.model.FtpSubscription ftpSubscription);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ca.efendi.datafeeds.model.FtpSubscription> toCacheModel();

	@Override
	public ca.efendi.datafeeds.model.FtpSubscription toEscapedModel();

	@Override
	public ca.efendi.datafeeds.model.FtpSubscription toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}